### ISSUE TITLE
NoClassDefFounfError after updating version to 7.0.0

### ISSUE THREAD

**Issue by c-a-narain** [TIBCOSoftware/jasperreports#449]
Recently I have update my jasperreport version to 7.0.0

After that I am facing an new exception 

`java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/component/XmlDigesterConfigurer` 

In my console and I couldn't able to find the XmlDigesterConfigurer file in the JAR. is the file removed in the release ? someone please help me to resolve this error in my project

**Comment by dadza** [comment]
net/sf/jasperreports/engine/component/XmlDigesterConfigurer has indeed been removed in JasperReports 7.0.0.

You probably have a jar that contains a JasperReports component implementation on your application's classpath.  JasperReports 7.0.0 is not compatible with old component implementations, you'll need updated component jars that are compatible with 7.0.0.

Include a listing of jars used in your application and the full exception stacktrace to identify the exact source of the error.

**Comment by c-a-narain** [comment]
Thank you I will look into the classpath of the application

**Comment by c-a-narain** [comment]
> net/sf/jasperreports/engine/component/XmlDigesterConfigurer has indeed been removed in JasperReports 7.0.0.
> 
> You probably have a jar that contains a JasperReports component implementation on your application's classpath. JasperReports 7.0.0 is not compatible with old component implementations, you'll need updated component jars that are compatible with 7.0.0.
> 
> Include a listing of jars used in your application and the full exception stacktrace to identify the exact source of the error.

Looks like `JRPdfExporter` was also removed in 7.0.0 which one should I use as an alternative

**Comment by dadza** [comment]
JRPdfExporter was not removed, it was moved to a separate jar at https://repo1.maven.org/maven2/net/sf/jasperreports/jasperreports-pdf/
