### ISSUE TITLE
NoClassDefFoundError occurs when updating to 6.20.2

### ISSUE THREAD

**Issue by yu-shiba** [TIBCOSoftware/jasperreports#347]
In the update to `6.20.2`, the following error occurs when exporting PDFs
```
Caused by: java.lang.NoClassDefFoundError: com/lowagie/text/DocumentException
	at net.sf.jasperreports.export.pdf.classic.ClassicPdfProducerFactory.createProducer(ClassicPdfProducerFactory.java:44)
	at net.sf.jasperreports.engine.export.JRPdfExporter.createPdfProducer(JRPdfExporter.java:821)
	at net.sf.jasperreports.engine.export.JRPdfExporter.initExport(JRPdfExporter.java:716)
	at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:677)
```
This may be due to the fact that the dependency on openpdf has been changed to optional in this commit(100b25889ca86d1475c7facd6f332d3071104d3e).

Why was the dependency on openpdf changed to optional in 6.20.2?

**Comment by teodord** [comment]
Hi,

It was made option because it is optional. JasperReports can very well be used without ever exporting anything to PDF.

Thank you,
Teodor

**Comment by yu-shiba** [comment]
Hi, @teodord, 
I think this issue will work if openpdf is added as a dependency.
However, it is usually difficult for library users to figure out the dependencies that make a particular feature work correctly.

The Gradle article discusses the same issue.
[Optional dependencies are not optional](https://blog.gradle.org/optional-dependencies)

I think the way it should be is to divide the project into small parts like Spring framework so that dependencies can be added for each feature, but it's not that easy.

For now, our project will add openpdf dependencies to avoid the problem. (We also have this issue #339, so the dependencies are troublesome.)

Thank you very much.

**Comment by yu-shiba** [comment]
#351

**Comment by yu-shiba** [comment]
#350

**Comment by teodord** [comment]
The release 6.20.4 was published to put back mandatory OpenPDF dependency in pom.xml.
