### ISSUE TITLE
Various NoClassDefFound Exceptions for com.lowagie.text and NullPointerExceptions after updating to 6.20.2

### ISSUE THREAD

**Issue by DManstrator** [TIBCOSoftware/jasperreports#348]
After updating from 6.20.1 to 6.20.2 / 6.20.3, I get various `NoClassDefFound Exceptions` in our CI.

- `NoClassDefFound com/lowagie/text/DocumentException`
- `NoClassDefFound com/lowagie/text/SplitCharacter`

## Stacktraces

<details>
<summary>CI StackTrace SplitCharacter</summary>

```log
java.lang.NoClassDefFoundError: com/lowagie/text/SplitCharacter
	at net.sf.jasperreports.export.pdf.classic.ClassicPdfProducerFactory.createProducer(ClassicPdfProducerFactory.java:44)
	at net.sf.jasperreports.engine.export.JRPdfExporter.createPdfProducer(JRPdfExporter.java:821)
	at net.sf.jasperreports.engine.export.JRPdfExporter.initExport(JRPdfExporter.java:716)
	at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:677)
	at <our code> (see CI code below)
        [...]
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.SplitCharacter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 79 more
```
</details>

<details>
<summary>CI StackTrace DocumentException</summary>

```log
java.lang.NoClassDefFoundError: com/lowagie/text/DocumentException
	at net.sf.jasperreports.export.pdf.classic.ClassicPdfProducerFactory.createProducer(ClassicPdfProducerFactory.java:44)
	at net.sf.jasperreports.engine.export.JRPdfExporter.createPdfProducer(JRPdfExporter.java:821)
	at net.sf.jasperreports.engine.export.JRPdfExporter.initExport(JRPdfExporter.java:716)
	at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:677)
	at <our code> (see CI code below)
        [...]
Caused by: java.lang.ClassNotFoundException: com.lowagie.text.DocumentException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 104 more
```
</details>

### Different behaviour when executing it locally

When running the failing tests locally, I get an NPE instead.

<details>
<summary>Local StackTrace SplitCharacter</summary>

```log
java.lang.NullPointerException
	at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2865)
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2881)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3378)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:942)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:385)
	at net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.<init>(ContextClassLoaderObjectInputStream.java:56)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:225)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:210)
	at <our code> (see local code below)
        [...]
```
</details>

## Code

<details>
<summary>Code which fails in the CI</summary>

```java
public void generate([...], final OutputStream outputStream) throws JRException {
    [...]

    final List<JasperPrint> jasperPrintList = new ArrayList<>();
    [...]

    final JRPdfExporter exporter = new JRPdfExporter();
    exporter.setExporterInput(SimpleExporterInput.getInstance(jasperPrintList));
    exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(outputStream));
    exporter.exportReport();  // <-- Fails here (see StackTrace above).
}
```
</details>

<details>
<summary>Code which fails locally</summary>

```java
public JasperReport getReport(final String reportName, final String section) {
    return compiledReports.computeIfAbsent(reportName + '/' + section, s -> {
        final String jasperFileName =
                TEMPLATES_FOLDER + reportName + '/' + section + JASPER_REPORTS_EXTENSION;
        try (final InputStream inputStream = getClass().getResourceAsStream(jasperFileName)) {
            return (JasperReport) JRLoader.loadObject(inputStream);  // <-- Fails here (see StackTrace above).
        } catch (final JRException e) {
            throw new RenderingFailedException(THE_REPORT_COULD_NOT_BE_GENERATED, e);
        } catch (final IOException e) {
            throw new RenderingFailedException(TEMPLATE_NOT_FOUND, e);
        }
    });
}
```
</details>

## Information

I'm using Java 11 and Maven 3.9.1 in the project. Do you need any additional information?

**Comment by teodord** [comment]
OpenPDF is an optional dependency in JasperReports Library, just like many others:
https://github.com/TIBCOSoftware/jasperreports/blob/master/jasperreports/pom.xml#L73
If you export to PDF in your application, you need to add it explicitely.

Thank you,
Teodor

**Comment by DManstrator** [comment]
After I added the OpenPDF in version 1.3.30, I get different a different exception now.

> java.lang.NoSuchMethodError: com.lowagie.text.Document.setGlyphSubstitutionEnabled(Z)V

The problem: In `ClassicPdfProducer` you call [Document#setGlyphSubstitutionEnabled](https://github.com/TIBCOSoftware/jasperreports/blob/6.20.3/jasperreports/src/net/sf/jasperreports/export/pdf/classic/ClassicPdfProducer.java#L121-L128). But this method does not exist in [OpenPDF v1.3.30](https://github.com/LibrePDF/OpenPDF/blob/1.3.30/openpdf/src/main/java/com/lowagie/text/Document.java).

Am I supposted to use version 1.3.30.jaspersoft.2 and if so, how would I do so?

**Comment by soc** [comment]
I just wanted to file a new issue on this, but I guess @DManstrator has already reported the symptoms. Here is how it looks for me:

![jasper-nsme](https://user-images.githubusercontent.com/42493/233863818-6628127c-27cd-4699-88cc-c13364acbeba.png)

**Comment by teodord** [comment]
JasperReports pom.xml has an additional Maven repository from which we get the customized third-party artifacts:
https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/

See it being mentioned in the JRL pom file here:
https://search.maven.org/artifact/net.sf.jasperreports/jasperreports/6.20.3/jar

**Comment by DManstrator** [comment]
I honestly don't think it was a good idea to make OpenPDF optional **as a Patch Update**. It currently requires a very special version which is only available with a specific Maven repository. So it could break the build in a lot of projects using the PDF export.

About the special version: From what I've seen in #339 you say that you're still waiting for a PR to get merged before you can use the normal version again. Since the original author of that PR does not respond anymore, I recreated it. Hopefully, that will speed it up for you.

> See it being mentioned in the JRL pom file here: https://search.maven.org/artifact/net.sf.jasperreports/jasperreports/6.20.3/jar

fyi: When I open the page, I'm getting automatically redirected to https://central.sonatype.com/artifact/net.sf.jasperreports/jasperreports/6.20.3?smo=true (Status Code 307: Temporary Redirect). 

Guess you wanted to show how to use the repository. It should be like that:

```xml
<repositories>
  <repository>
    <id>jaspersoft-third-party</id>
    <url>https://jaspersoft.jfrog.io/jaspersoft/third-party-ce-artifacts/</url>
  </repository>
</repositories>
```

When using the repository, OpenPDF in version `1.3.30.jaspersoft.2` can be used.

**Comment by teodord** [comment]
The release 6.20.4 was published to put back mandatory OpenPDF dependency in pom.xml.
