### ISSUE TITLE
7.0.0 compiler issues

### ISSUE THREAD

**Issue by maqjav** [TIBCOSoftware/jasperreports#458]
After updating to 7.0.0, if I try to compile a JRXML in my Tomcat, the compiler throws errors like this one:

```
C:\Programas\Eclipse_2024_06\Report_3a1b5bfd15e0dc9fdba1f2709da2c083a257b4dae7705cb437f62b2c64d25153.java:4: error: package net.sf.jasperreports.engine does not exist
import net.sf.jasperreports.engine.*;
^
C:\Programas\Eclipse_2024_06\Report_3a1b5bfd15e0dc9fdba1f2709da2c083a257b4dae7705cb437f62b2c64d25153.java:5: error: package net.sf.jasperreports.engine.fill does not exist
import net.sf.jasperreports.engine.fill.*;
```
**The error doesn't appear if I run the code with Junit in Eclipse, so I assume the problem is that I'm missing a dependency, however I cannot find which one.**

This is the code used (same we were using with 6.21.3 without issues).

```
try (InputStream in = this.getClass().getResourceAsStream(this.getTemplateFile())) {
	final JasperDesign jd = JRXmlLoader.load(in);
	final JasperReport jr = JasperCompileManager.compileReport(jd);
}
```
I tried adding [ECJ](https://mvnrepository.com/artifact/org.eclipse.jdt/ecj/3.38.0) to the project, but the error remains, however according to the [compile dependencies list](https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports/7.0.0), this one is not required anymore since 7.0.0.

I'm not sure what dependency it's missing. 
* Where can I find the documentation related to the new dependencies used in 7.0.0?
* What dependency do I need to be able to compile JRXMLs in my tomcat?

Thanks.

**Comment by dadza** [comment]
The report compiler based on ECJ has been extracted to a separate artifact called [jasperreports-jdt](https://central.sonatype.com/artifact/net.sf.jasperreports/jasperreports-jdt/versions)

Adding a dependency to jasperreports-jdt would fix the problem.  ECJ will come as a transitive dependency.

**Comment by maqjav** [comment]
It worked, thanks!

Is there a document explaining all the new artifacts created for 7.0.0? I've been looking for it the whole morning and I couldn't find it anywhere, that's why I decided to come here to ask. Without it it's hard to tell what artifacts we might need after upgrading to 7.0.0.

**Comment by SATISHEEEK** [comment]
> It worked, thanks!
> 
> Is there a document explaining all the new artifacts created for 7.0.0? I've been looking for it the whole morning and I couldn't find it anywhere, that's why I decided to come here to ask. Without it it's hard to tell what artifacts we might need after upgrading to 7.0.0.

Agree guys. I am facing a similiar issue while migrating. Its difficult to identify a missing dependency. Do you have some documentation or a recommended process how to identify which depedency we might need? 

Thanks for answer!
