### ISSUE TITLE
Issue upgrading from 6.20.0 to 6.20.5

### ISSUE THREAD

**Issue by javiiker** [TIBCOSoftware/jasperreports#376]
Hi,

We are facing some weird issue from switching from 6.20.0 to 6.20.5. Although 6.20.5 is already including openpdf-1.3.30.jaspersoft.2.jar, when trying to export a PDF from a jasper template (rebuild with Jasper Studio 6.20.5), jasperreports is throwing the following error:

	java.lang.NoSuchMethodError: 'boolean com.lowagie.text.Phrase.add(com.lowagie.text.Element)'
		at net.sf.jasperreports.export.pdf.classic.ClassicPhrase.add(ClassicPhrase.java:56)
		at net.sf.jasperreports.engine.export.JRPdfExporter.getPhrase(JRPdfExporter.java:2510)
		at net.sf.jasperreports.engine.export.SimplePdfTextRenderer.renderParagraph(SimplePdfTextRenderer.java:184)
		at net.sf.jasperreports.engine.export.AbstractTextRenderer.render(AbstractTextRenderer.java:389)
		at net.sf.jasperreports.engine.export.SimplePdfTextRenderer.render(SimplePdfTextRenderer.java:122)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportText(JRPdfExporter.java:2792)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportElements(JRPdfExporter.java:1303)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportPage(JRPdfExporter.java:1240)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportReportToStream(JRPdfExporter.java:1133)
		at net.sf.jasperreports.engine.export.JRPdfExporter.exportReport(JRPdfExporter.java:702)
		at net.sf.jasperreports.engine.JasperExportManager.exportToPdf(JasperExportManager.java:217)
		at net.sf.jasperreports.engine.JasperRunManager.runToPdf(JasperRunManager.java:244)
		at net.sf.jasperreports.engine.JasperRunManager.runReportToPdf(JasperRunManager.java:723)

I have read previous issues and I know this was a common issue before 6.20.4, but in our case openpdf lib is correctly in the classpath, so don't know why jasperreport 6.20.5 is still trying to look for itext library instead of openpdf one.

The call we are using is very simple

` byte[] bytes = JasperRunManager.runReportToPdf(sourceFileName, parameters, db.getConnection());`

The only thing I have found is that our project is using itext 1.2.7 library as a dependency of other library. So don't know if that is creating confusion to jasperreports lib.

Current mvn dependency:

[INFO] +- net.sf.jasperreports:jasperreports:jar:6.20.5:compile
[INFO] |  +- com.github.librepdf:openpdf:jar:1.3.30.jaspersoft.2:compile
[INFO] |  +- org.jfree:jcommon:jar:1.0.23:compile
[INFO] |  +- org.jfree:jfreechart:jar:1.0.19:compile
[INFO] |  \- org.eclipse.jdt:ecj:jar:3.21.0:compile

Thanks!

**Comment by dadza** [comment]
Having both iText and OpenPDF as dependencies in an application does create confusion as OpenPDF has the same package/class names as iText.  So when you have both the application will actually use the one that comes first in the classpath, which in your case seems to be iText (maybe the classpath is ordered by jar file name).

One thing that you could try is to exclude iText as dependency from your application, it might be that the library that depends on iText will work with OpenPDF as well.

Regards,
Lucian

**Comment by javiiker** [comment]
Hi,

Thanks! That has sense. I will follow your suggestion and exclude iText dependency.

Thank you again.

Javi
